import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home({ data }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {data.map(data => <li key={data.id}>{data.name}</li>)}
    </div>
  )
}


export async function getServerSideProps() {
  const res = await fetch(`https://jsonplaceholder.typicode.com/users`)
  const data = await res.json()
  console.log("🚀 ~ file: index.js ~ line 75 ~ getServerSideProps ~ data", data)
  return {
    props: { data }, // will be passed to the page component as props
  }
}